ALTER SESSION SET CONTAINER = MYORADB1;
CREATE USER MY_USER IDENTIFIED BY "PWD GOES HERE";
GRANT DBA TO MY_USER;
ALTER USER MY_USER QUOTA UNLIMITED ON users;
SELECT * FROM dba_role_privs WHERE grantee = 'MY_USER';


