services:
  oracle-db:
    image: oracle-local  # Replace with your image name and tag
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_SID: MYORADB
      ORACLE_PDB: MYORADB1
      ORACLE_PWD: ChangeMe123  # Default password for SYS, SYSTEM, and other initial users
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./init-scripts:/opt/oracle/scripts/startup
    healthcheck:
      test: ["CMD", "sqlplus", "-silent", "sys/ChangeMe123//localhost:1521/MYORADB as sysdba", "EXIT"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle-data:
    external: true

